import type { Metadata } from "next";

import "./globals.css";
import { RobotoFont } from "@/styles/fonts";
import { cn } from "@/utils/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          RobotoFont.className,
          "bg-neutral-foreground text-font-default"
        )}
      >
        {children}
      </body>
    </html>
  );
}
