import type { Metadata } from "next"

import { RobotoFont } from "@/styles/fonts"
import { cn } from "@/utils/cn"

import "./globals.css"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(RobotoFont.className, "bg-neutral-foreground text-font-default")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
